version: '3'


services:
  cassandra:
    image: cassandra
    ports:
      - "9042:9042"
  kafka:
    image: wurstmeister/kafka

  app1:
    depends_on:
      - cassandra
      - kafka
    build: ./web
    ports:
      - "80:80"
    links:
      - cassandra
      - kafka

  spark:
    image: jupyter/pyspark-notebook
    depends_on:
      - cassandra
      - kafka
    links:
      - cassandra
      - kafka
