version: '2.0'


services:
  cassandra:
    image: cassandra
    ports:
      - "9042:9042"
  kafka:
    image: wurstmeister/kafka

  app:
    depends_on:
      - cassandra
      - kafka
    build: "./web"
    links:
      - cassandra
      - kafka

  spark:
    image: jupyter/pyspark-notebook
    depends_on:
      - cassandra
      - kafka
    links:
      - cassandra
      - kafka
